# Dependencies
markdown: rdiscount
pygments: true

# Permalinks
permalink: "/blog/:year/:month/:day/:title"

# Server
destination:      ./_gh_pages
exclude:          [".gitignore", "README.md", "less"]
port:             9001